In [4]:
import IonQCompiler as compiler

from braket.circuits import Circuit, Gate, Instruction, circuit, Observable
import numpy as np
circ = Circuit()
circ = Circuit().h(range(10))

c = compiler.IonQCompiler()
braket_circ = c.compile(circ)

#print(braket_circ.add_circuit(braket_circ))



OPENQASM 2.0;
include "qelib1.inc";
qreg q[10];
creg b[10];
ry(pi/2) q[0];
rx(pi) q[0];
ry(pi/2) q[1];
rx(pi) q[1];
ry(pi/2) q[2];
rx(pi) q[2];
ry(pi/2) q[3];
rx(pi) q[3];
ry(pi/2) q[4];
rx(pi) q[4];
ry(pi/2) q[5];
rx(pi) q[5];
ry(pi/2) q[6];
rx(pi) q[6];
ry(pi/2) q[7];
rx(pi) q[7];
ry(pi/2) q[8];
rx(pi) q[8];
ry(pi/2) q[9];
rx(pi) q[9];
measure q[0] -> b[0];
measure q[1] -> b[1];
measure q[2] -> b[2];
measure q[3] -> b[3];
measure q[4] -> b[4];
measure q[5] -> b[5];
measure q[6] -> b[6];
measure q[7] -> b[7];
measure q[8] -> b[8];
measure q[9] -> b[9];
10
('y', 1.5707963267948966, [0])
('x', 3.141592653589793, [0])
('y', 1.5707963267948966, [1])
('x', 3.141592653589793, [1])
('y', 1.5707963267948966, [2])
('x', 3.141592653589793, [2])
('y', 1.5707963267948966, [3])
('x', 3.141592653589793, [3])
('y', 1.5707963267948966, [4])
('x', 3.141592653589793, [4])
('y', 1.5707963267948966, [5])
('x', 3.141592653589793, [5])
('y', 1.5707963267948966, [6])
('x', 3.141592653589793, [6])
('y', 1.57

In [2]:
Circuit().gpi2(0,1.57).rx(0,0).as_unitary()

array([[ 0.70710678+0.j        , -0.70710656-0.00056309j],
       [ 0.70710656-0.00056309j,  0.70710678+0.j        ]])

In [5]:
np.round(braket_circ.as_unitary(),3)

array([[ 0.031-0.j,  0.031-0.j,  0.031-0.j, ...,  0.031-0.j,  0.031-0.j,
         0.031+0.j],
       [ 0.031-0.j, -0.031+0.j,  0.031-0.j, ..., -0.031+0.j,  0.031+0.j,
        -0.031-0.j],
       [ 0.031-0.j,  0.031-0.j, -0.031+0.j, ...,  0.031+0.j, -0.031+0.j,
        -0.031-0.j],
       ...,
       [ 0.031-0.j, -0.031+0.j,  0.031+0.j, ..., -0.031-0.j,  0.031+0.j,
        -0.031-0.j],
       [ 0.031-0.j,  0.031+0.j, -0.031+0.j, ...,  0.031+0.j, -0.031-0.j,
        -0.031-0.j],
       [ 0.031+0.j, -0.031-0.j, -0.031-0.j, ..., -0.031-0.j, -0.031-0.j,
         0.031+0.j]])

In [8]:
np.round(Circuit().h(range(10)).as_unitary(),10)

array([[ 0.03125+0.j,  0.03125+0.j,  0.03125+0.j, ...,  0.03125+0.j,
         0.03125+0.j,  0.03125+0.j],
       [ 0.03125+0.j, -0.03125+0.j,  0.03125+0.j, ..., -0.03125+0.j,
         0.03125+0.j, -0.03125+0.j],
       [ 0.03125+0.j,  0.03125+0.j, -0.03125+0.j, ...,  0.03125+0.j,
        -0.03125+0.j, -0.03125+0.j],
       ...,
       [ 0.03125+0.j, -0.03125+0.j,  0.03125+0.j, ..., -0.03125+0.j,
         0.03125+0.j, -0.03125+0.j],
       [ 0.03125+0.j,  0.03125+0.j, -0.03125+0.j, ...,  0.03125+0.j,
        -0.03125+0.j, -0.03125+0.j],
       [ 0.03125+0.j, -0.03125+0.j, -0.03125+0.j, ..., -0.03125+0.j,
        -0.03125+0.j,  0.03125+0.j]])

In [16]:
a*np.conj(np.transpose(a))

array([[0.5+0.j, 0.5+0.j],
       [0.5+0.j, 0.5+0.j]])

In [18]:
a*a

array([[ 0.5+0.j, -0.5-0.j],
       [-0.5-0.j,  0.5+0.j]])

In [96]:

from braket.devices import LocalSimulator
from braket.aws import AwsDevice
from braket.device_schema.device_action_properties import DeviceActionType
import numpy as np


test = Circuit().x(0).add(braket_circ)

print(test)

device = LocalSimulator()

res = device.run(test, shots = 1000).result()

print(res.measurement_counts)

TypeError: x() missing 1 required positional argument: 'target'